# Docker version
version: '2'
services:
    # DNS container
    dns-environment:
        container_name: ns
        # Build custom DNS image and environment
        build:
            context: ./DNS
            dockerfile: Dockerfile
        # Port mapping from ns server (53) to host (53)
        ports:
            - 53:53/udp
            - 53:53/tcp
        dns:
            - 172.16.10.2
        networks:
            default:
                ipv4_address: 172.16.20.3
networks:
    default:
      external:
        name: dmz


# docker-compose -f dns.yml down
# docker network create --driver bridge --subnet 172.16.20.0/24 --gateway 172.16.20.254 dmz
# docker network create --driver bridge --subnet 172.16.10.0/24 --gateway 172.16.10.254 intranet
# docker-compose -f dns.yml -p service_dns up -d --build