# Docker version
version: '2'
services:
    # PHP Apache Web Server
    php-apache-environment:
        container_name: php-apache
        # Build custom PHP Apache image and environment
        build:
            context: ./WEB-HTTPS
            dockerfile: Dockerfile
        hostname: daxhelet.ovh
        restart: always
        depends_on:
            - db
        volumes:
            - ./WEB-HTTPS/etcletsencrypt:/etc/letsencrypt
            - ./WEB-HTTPS/varletsencrypt:/var/lib/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        dns:
            - 172.16.10.3
        environment:
            LETS_ENCRYPT_EMAIL: "he201753@students.ephec.be"
            LETS_ENCRYPT_DOMAINS: "daxhelet.ovh,www.daxhelet.ovh,b2b.daxhelet.ovh"
        networks:
            woodytoys:
                ipv4_address: 172.16.20.2
    # MySQL containerkey
    db:
        container_name: db
        build:
            context: ./WEB-HTTPS/MySQL
            dockerfile: Dockerfile
        # Restarts the service whenever any defined configuration changes
        restart: always
        # Environment Variables Setup
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: b2b
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        dns:
            - 172.16.10.3
        networks:
            woodytoys:
                ipv4_address: 172.16.10.5
    # DNS container
    dns-environment:
        container_name: ns
        # Build custom DNS image and environment
        build:
            context: ./DNS
            dockerfile: Dockerfile
        # Port mapping from ns server (53) to host (53)
        ports:
            - 53:53/udp
            - 53:53/tcp
        dns:
            - 172.16.10.3
        networks:
            woodytoys:
                ipv4_address: 172.16.20.4
    # DNS Resolver
    resolver-environment:
        container_name: resolver
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/RESOLVER
            dockerfile: Dockerfile
        networks:
            woodytoys:
                ipv4_address: 172.16.10.3
    # INTERNAL DNS container
    internal-dns-environment:
        container_name: internal-ns
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/DNS
            dockerfile: Dockerfile
        networks:
            woodytoys:
                ipv4_address: 172.16.10.2
    # ERP PHP Apache container
    erp-environment:
        container_name: erp
        # Build custom PHP Apache image and environment
        build:
            context: ./SERVICES_INTERNES/ERP
            dockerfile: Dockerfile
        depends_on:
            - db
        # Present Working Directory Setup :
        #   copy all files from ./WEB/src/b2b to /var/www/html inside the container
        volumes:
            - ./SERVICES_INTERNES/ERP/src/b2b:/usr/local/apache2/htdocs/b2b/
        dns:
            - 172.16.10.3
        networks:
            woodytoys:
                ipv4_address: 172.16.10.4
    ### POSTES UTILISATEURS
    # DIRECTION
    direction-environment:
        container_name: direction
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/DIRECTION
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            woodytoys:
                ipv4_address: 172.16.0.2
    # SECRETARIAT
    secretariat-environment:
        container_name: secretariat
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/SECRETARIAT
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            woodytoys:
                ipv4_address: 172.16.0.3
    # COMPTABILITE
    comptabilite-environment:
        container_name: comptabilite
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/COMPTABILITE
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            woodytoys:
                ipv4_address: 172.16.0.4
    # COMMERCIAUX
    commerciaux-environment:
        container_name: commerciaux
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/COMMERCIAUX
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            woodytoys:
                ipv4_address: 172.16.0.5
    # OUVRIERS
    commerciaux-environment:
        container_name: ouvriers
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/OUVRIERS
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            woodytoys:
                ipv4_address: 172.16.0.6
networks:
    woodytoys:
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/16
