# Docker version
version: '2'
services:
    # PHP Apache container
    php-apache-environment:
        container_name: php-apache
        # Build custom PHP Apache image and environment
        build:
            context: ./WEB
            dockerfile: Dockerfile
        depends_on:
            - db
        # Present Working Directory Setup :
        #   copy all files from ./WEB/src/b2b to /var/www/html inside the container
        volumes:
            - ./WEB/src/b2b:/usr/local/apache2/htdocs/b2b/
            - ./WEB/src/www:/usr/local/apache2/htdocs/www/
        # Port mapping from Apache (80) to host (8000)
        ports:
            - 80:80
        networks:
            woodytoys:
                ipv4_address: 172.16.20.1
    # MySQL containerkey
    db:
        container_name: db
        image: mysql
        # Restarts the service whenever any defined configuration changes
        restart: always
        # Environment Variables Setup
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: b2b
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        # Port mapping from MySQL (3306) to host (9906)
        ports:
            - 9906:3306
        networks:
            woodytoys:
                ipv4_address: 172.16.10.4
    # MySQL Handler
    phpmyadmin:
        container_name: phpmyadmin 
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        # Restarts the service whenever any defined configuration changes
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    # DNS container
    dns-environment:
        container_name: ns
        # Build custom DNS image and environment
        build:
            context: ./DNS
            dockerfile: Dockerfile
        # Port mapping from ns server (53) to host (53)
        ports:
            - 53:53/udp
            - 53:53/tcp
        networks:
            woodytoys:
                ipv4_address: 172.16.20.3
    # DNS Resolver
    resolver-environment:
        container_name: resolver
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/RESOLVER
            dockerfile: Dockerfile
        networks:
            woodytoys:
                ipv4_address: 172.16.10.2
    # INTERNAL DNS container
    internal-dns-environment:
        container_name: internal-ns
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/DNS
            dockerfile: Dockerfile
        networks:
            woodytoys:
                ipv4_address: 172.16.10.1
networks:
    woodytoys:
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/16