# Docker version
version: '2'
services:
    # DNS Resolver
    resolver-environment:
        container_name: resolver
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/RESOLVER
            dockerfile: Dockerfile
        networks:
            default:
                ipv4_address: 172.16.10.3
    # INTERNAL DNS container
    internal-dns-environment:
        container_name: internal-ns
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/DNS
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            default:
                ipv4_address: 172.16.10.2
    ### POSTES UTILISATEURS
    # DIRECTION
    direction-environment:
        container_name: direction
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/DIRECTION
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            lan-interne:
                ipv4_address: 172.16.0.2
    # SECRETARIAT
    secretariat-environment:
        container_name: secretariat
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/SECRETARIAT
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            lan-interne:
                ipv4_address: 172.16.0.3
    # COMPTABILITE
    comptabilite-environment:
        container_name: comptabilite
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/COMPTABILITE
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            lan-interne:
                ipv4_address: 172.16.0.4
    # COMMERCIAUX
    commerciaux-environment:
        container_name: commerciaux
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/COMMERCIAUX
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            lan-interne:
                ipv4_address: 172.16.0.5
    # OUVRIERS
    commerciaux-environment:
        container_name: ouvriers
        # Build custom DNS image and environment
        build:
            context: ./SERVICES_INTERNES/POSTES_UTILISATEURS/OUVRIERS
            dockerfile: Dockerfile
        dns:
            - 172.16.10.3
        networks:
            lan-interne:
                ipv4_address: 172.16.0.6
networks:
    default:
        external:
            name: intranet
    lan-interne:
        external: true

# docker-compose -f services_internes.yml down
# docker network create --driver bridge --subnet 172.16.20.0/24 --gateway 172.16.20.254 dmz
# docker network create --driver bridge --subnet 172.16.10.0/24 --gateway 172.16.10.254 intranet
# docker network create --driver bridge --subnet 172.16.0.0/24 --gateway 172.16.0.254 lan-interne
# docker-compose -f services_internes.yml -p services_internes up -d --build