version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
        - checkout
        - run: 
          name: Execute docker-compose
          command: |
            cd WEB
            docker-compose up
        - run:
          name: Deploy to OVH VPS
          command: |
            ssh -oStrictHostKeyChecking=no -v $USER@$IP "/bin/bash ~/ADMIN_2TL1-7/deploy_app.sh"